payload = {
  /* Required fields */
  "display_name": "TEMPLATE_NAME",  ///
  "language": "English" | "Hindi" | "Spanish" | "French" | "German" | "Portuguese" | "Arabic" | "Bengali" | "Gujarati" | "Kannada" | "Malayalam" | "Marathi" | "Punjabi" | "Tamil" | "Telugu" | "Urdu", /* other supported languages */
  "category": "UTILITY" | "MARKETING" | "AUTHENTICATION", //

  /* Body (Required) */
  "body": "Hi *{{1}}*, your order #{{2}} worth ₹{{3}} is confirmed! 🎉", //
  "body_text": ["John Doe", "12345", "1999.50"], // Sample values for placeholders

  /* Header (Optional) */
  "header_format": "NONE" | "TEXT" | "IMAGE" | "VIDEO" | "DOCUMENT",
  
  // If header_format: TEXT
  "header": "Order Confirmation for {{1}}", 
  "header_text": ["Premium Customer"],

  // If header_format: IMAGE
  "header_handle": ["image_handle_from_upload_api"],
  "header_handle_file_url": "https://example.com/image.jpg",
  "header_handle_file_name": "product_image.jpg",

  // If header_format: VIDEO  
  "header_handle": ["video_handle_from_upload_api"],
  "header_handle_file_url": "https://example.com/video.mp4", 
  "header_handle_file_name": "product_video.mp4",

  // If header_format: DOCUMENT
  "header_handle": ["document_handle_from_upload_api"],
  "header_handle_file_url": "https://example.com/invoice.pdf",
  "header_handle_file_name": "invoice_12345.pdf",

  /* Footer (Optional) */
  "footer": "Thank you for choosing us! 🙏",

  /* Buttons (Optional) */
  "button_type": "NONE" | "QUICK_REPLY" | "CALL_TO_ACTION",

  // If button_type: QUICK_REPLY (max 3 buttons)
  "buttons": [
    {
      "type": "QUICK_REPLY",
      "text": "Track Order"
    },
    {
      "type": "QUICK_REPLY", 
      "text": "Cancel Order"
    },
    {
      "type": "QUICK_REPLY",
      "text": "Contact Support"
    }
  ],

  // If button_type: CALL_TO_ACTION (max 2 buttons, 1 of each type)
  "buttons": [
    {
      "type": "PHONE_NUMBER",
      "text": "Call Support",
      "phone_number": "+919876543210"
    },
    {
      "type": "URL", 
      "text": "Track Order",
      "url": "https://yourstore.com/track/{{1}}" // Can have 1 placeholder max
    }
  ],

  /* Mixed Call to Action (1 URL + 1 Phone) */
  "buttons": [
    {
      "type": "URL",
      "text": "View Order", 
      "url": "https://yourstore.com/orders/{{1}}",
      "url_text": ["12345"] // Sample placeholder value
    },
    {
      "type": "PHONE_NUMBER",
      "text": "Call Us",
      "phone_number": "+919876543210"
    }
  ],

  /* Additional Optional Fields */
  "template_id": "auto_generated_by_interakt", // Read-only, generated by Interakt
  "status": "PENDING" | "APPROVED" | "REJECTED", // Read-only, set by WhatsApp
  "rejection_reason": "Policy violation details", // Read-only, if rejected
  
  /* Metadata (Optional) */
  "tags": ["order", "confirmation", "ecommerce"],
  "description": "Template for order confirmation messages",
  
  /* Advanced Options (Optional) */
  "allow_category_change": true | false, // Allow changing category after creation
  "created_at": "2024-01-15T10:30:00Z", // Read-only timestamp
  "updated_at": "2024-01-15T10:30:00Z", // Read-only timestamp
  
  /* Localization (Optional for multi-language templates) */
  "localizations": [
    {
      "language": "Hindi",
      "body": "नमस्कार *{{1}}*, आपका ऑर्डर #{{2}} ₹{{3}} का कन्फर्म हो गया है!",
      "body_text": ["राम शर्मा", "12345", "1999.50"],
      "header": "ऑर्डर कन्फर्मेशन {{1}} के लिए",
      "header_text": ["प्रीमियम ग्राहक"],
      "footer": "हमें चुनने के लिए धन्यवाद!"
    }
  ],

  /* Rate Limiting (Optional) */
  "rate_limit": {
    "max_per_day": 1000,
    "max_per_hour": 100
  },

  /* Template Variables Info (Optional metadata) */
  "variables": [
    {
      "name": "customer_name", 
      "position": 1,
      "type": "TEXT",
      "example": "John Doe"
    },
    {
      "name": "order_number",
      "position": 2, 
      "type": "TEXT",
      "example": "12345"
    },
    {
      "name": "order_amount",
      "position": 3,
      "type": "CURRENCY", 
      "example": "1999.50"
    }
  ]
}